Traceback (most recent call last):
  File "C:\Users\ic\AppData\Roaming\Python\Python312\site-packages\botasaurus\browser_decorator.py", line 163, in run_task
    result = func(driver, data)
             ^^^^^^^^^^^^^^^^^^
  File "c:\Users\ic\Documents\Visa-Appointments-Punjab\main.py", line 99, in check_visa_appointments
    for credential in self.credentials:
                      ^^^^^^^^^^^^^^^^
AttributeError: 'VisaBotApp' object has no attribute 'credentials'
